pluginManagement {
	apply from: 'https://raw.githubusercontent.com/nokeedev/nokeebuild-plugins/refs/heads/main/init.gradle'
}

plugins {
	id 'nokeebuild.source-control-management'
}

rootProject.name = 'nokee-code-templates'

includeBuild 'templates-c-greeter'
includeBuild 'templates-cpp-greeter'
includeBuild 'templates-jni-greeter'
includeBuild 'templates-objc-greeter'
includeBuild 'templates-objcpp-greeter'
includeBuild 'templates-swift-greeter'

includeBuild 'templates-cpp-list'

sourceControlManagement {
	gitRepository(uri("https://github.com/gradle-plugins/source-elements.git"))
}
